Redux/Redux/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from Redux import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Redux_Music.urls'))
]



urlpatterns = urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Redux/Redux_Music/urls.py
from django.urls import path
from django.conf.urls import url
from django.views.static import serve
from Redux import settings
from .views import home, album, detail, music_list, album_list, SearchList

app_name = 'music'
urlpatterns = [
    path('', home, name='home'),
    url(r'^download/(?P<path>.*)$',serve,{'document_root':settings.MEDIA_ROOT}),
    path('detail-album/<slug:slug>', album, name='album'),
    path('detail-song/<slug:slug>', detail, name='detail'),
    path('all-music/page/<int:page>', music_list, name="music-list"),
    path('all-albums/page/<int:page>', album_list, name='album-list'),
    path('search/', SearchList.as_view(), name="search"),
    path("search/page/<int:page>", SearchList.as_view(), name="search")
]

Redux/Redux_Account/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


class User(AbstractUser):
    pass

Redux/Redux_Music/models.py
from django.db import models
from django.utils import timezone


#============My Manger================
class MusicManager(models.Manager):
    def overview(self):
        return self.filter(status=True)


class Album(models.Model):
    title = models.CharField(max_length=200, verbose_name='Album Name')
    desc = models.TextField(verbose_name='Artists Names')
    img = models.ImageField(upload_to="media", verbose_name='Image')
    slug = models.SlugField(max_length=200, verbose_name='Title in URL')
    status = models.BooleanField(default=False, verbose_name="Overview")
    position = models.IntegerField()

    def __str__(self):
        return self.title
    

    objects = MusicManager()


class Music(models.Model):
    title = models.CharField(max_length=100, verbose_name='Artist Name')
    desc = models.TextField(verbose_name='Music Name')
    slug = models.SlugField(max_length=100, verbose_name='Title in URL')
    img = models.ImageField(upload_to='media', verbose_name='Image')
    img2 = models.ImageField(upload_to='media', verbose_name='Image Slider', null=True, blank=True)
    album = models.ManyToManyField(Album, related_name="articles", null=True, blank=True)
    download = models.FileField(upload_to='media', verbose_name='Upload Download File', null=True, blank=True)
    publish = models.DateField(default=timezone.now, verbose_name='Publish Date')
    status = models.BooleanField(default=False, verbose_name="Overview")


    class Meta:
        verbose_name = "Music"
        verbose_name_plural = "Musics"


    def __str__(self):
        return self.title
    
    objects = MusicManager()

Redux/Redux_Account/views.py
from django.shortcuts import render

# Create your views here.

Redux/Redux_Music/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse
from django.core.paginator import Paginator
from .models import Music, Album
from django.views.generic import ListView
from django.db.models import Q



def home(request):
    context = {
        'musics': Music.objects.all().order_by('-id')[:5],
        'albums': Album.objects.all()[:5],
        'overview': get_object_or_404(Album.objects.overview()),
    }
    return render(request, 'home_page.html', context)


def music_list(request, page=1):
    music = Music.objects.all().order_by('-id')
    paginator = Paginator(music, 10)
    musics = paginator.get_page(page)
    context = {'musics': musics}
    return render(request, 'view_all_song.html', context)


def download(request, path):
    file_path=os.path.join(settings.MEDIA_ROOT, path)
    if os.path.exists(file_path):
        with open(file_path, 'rb')as fh:
            response = HttpResponse(fh.read(), content_type="application/download")
            response['Content-Disposition']='inline;filename='+os.path.basename(file_path)
            return response
    raise Http404


def album(request, slug):
    context = {
        'album': get_object_or_404(Album, slug=slug)
    }
    return render(request, 'detail_album.html', context)


def album_list(request, page=1):
    album = Album.objects.all().order_by('-id')
    paginator = Paginator(album, 10)
    albums = paginator.get_page(page)
    context = {'albums': albums}
    return render(request, 'view_all_album.html', context)


def detail(request, slug):
    context = {
        'detail': get_object_or_404(Music, slug=slug)
    }
    return render(request, 'detail_song.html', context)


class SearchList(ListView):
    paginate_by = 10
    template_name = 'search_list.html'

    def get_queryset(self):
        search = self.request.GET.get('q')
        or_lookup = (Q(title__icontains=search) | Q(desc__icontains=search))
        return Music.objects.filter(or_lookup)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['search'] = self.request.GET.get('q')
        return context

Redux/templates/detail_song.html
{% extends 'shared/_Main_Layout.html' %}
{% load static %}

{% block content %}

      <section id="parallex" class="parallax-window" style="background-image: url({{ detail.img.url }})">
            <div class="container-fluid h-100">
               <div class="row align-items-center justify-content-center h-100 parallaxt-details">
                  <div class="col-lg-4 r-mb-23">
                     <div class="text-left">
                        <a href="javascript:void(0);">
                        <h1 class="slider-text big-title title text-uppercase" data-animation-in="fadeInLeft"
                              data-delay-in="0.6">{{ detail.title }}</h1>
                        </a>
                        <div class="movie-time d-flex align-items-center mb-3">
                        </div>
                        <p>{{ detail.desc }}</p>
                        <p>{{ detail.publish }}</p>
                        <div class="parallax-buttons">
                           <a href="{{detail.download.url}}" download="{{detail.download.url}}" class="btn btn-hover">Download</a>
                        </div>
                     </div>
                  </div>
                  <div class="col-lg-8">
                     <div class="parallax-img">
                        <a href="movie-details.html">
                        	<img src="{{ detail.img.url }}" class="img-fluid w-100" alt="bailey">
                        </a>
                     </div>
                  </div>
               </div>
            </div>
         </section>
{% endblock %}

Redux/templates/search_list.html
{% extends 'shared/_Main_Layout.html' %}
{% load static %}
{% block content %}
   <!-- MainContent -->
   <div class="main-content">
      <section class="movie-detail container-fluid">
         
      </section>
      <section id="iq-favorites">
         <div class="container-fluid">
            <div class="block-space">
               <div class="row">
                  <div class="col-sm-12 overflow-hidden">
                     <div class="iq-main-header d-flex align-items-center justify-content-between">
                        <h4 class="main-title">All Songs</h4>
                     </div>
                  </div>
               </div>
               <div class="row">
               {% for music in object_list %}
                  <div class="col-1-5 col-md-6 iq-mb-30">
                     <div class="epi-box">
                        <div class="epi-img position-relative">
                           <img src="{{music.img.url}}" class="img-fluid img-zoom" alt="">
                           <div class="episode-play-info">
                              <div class="episode-play">
                                 <a href="{% url "music:detail" music.slug %}">
                                    <i class="ri-play-fill"></i>
                                 </a>
                              </div>
                           </div>
                        </div>
                        <div class="epi-desc p-3">
                           <div class="d-flex align-items-center justify-content-between">
                              <span class="text-white">{{music.title|truncatechars:15}}</span>
                           </div>
                           <a href="{% url "music:detail" music.slug %}">
                              <h6 class="epi-name text-white mb-0">{{music.desc|truncatechars:15}}
                              </h6>
                           </a>
                        </div>
                     </div>
                  </div>
                {% endfor %}  
               </div>
            </div>
         </div>
      </section>
   </div>   
   <nav class="d-flex justify-content-center" aria-label="Page navigation example">
        <ul class="pagination ">
            {% if page_obj.has_previous %}
            <li class="page-item"><a class="page-link bg-dark" href="{% url "music:search" page_obj.previous_page_number %}?q={{search}}">Previous</a></li>
            {% endif %}
            {% if page_obj.has_next %}
            <li class="page-item"><a class="page-link bg-dark" href="{% url 'music:search' page_obj.next_page_number %}?q={{search}}">Next</a></li>
            {% endif %}
        </ul>
   </nav>
{% endblock %}

Redux/templates/shared/Footer.html
    
    
    <footer class="mb-0">
         <div class="container-fluid">
            <div class="block-space">
               <div class="row">
                  <div class="col-lg-3 col-md-4">
                     <ul class="f-link list-unstyled mb-0">
                        <li><a href="{% url 'music:home' %}">Home</a></li>
                        <li><a href="{% url 'music:music-list' page=1 %}">All Songs</a></li>
                        <li><a href="{% url 'music:album-list' page=1 %}">All Albums</a></li>
                     </ul>
                  </div>
                  <div class="col-lg-3 col-md-4">
                     <ul class="f-link list-unstyled mb-0">
                        <li><a href="#">Privacy Policy</a></li>
                        <li><a href="#">Terms & Conditions</a></li>
                        <li><a href="#">Help</a></li>
                     </ul>
                  </div>
                  <div class="col-lg-3 col-md-4">
                     <ul class="f-link list-unstyled mb-0">
                        <li><a href="#">FAQ</a></li>
                        <li><a href="#">Cotact Us</a></li>
                        <li><a href="#">Legal Notice</a></li>
                     </ul>
                  </div>
                  <div class="col-lg-3 col-md-12 r-mt-15">
                     <div class="d-flex">
                        <a href="#" class="s-icon">
                        <i class="ri-telegram-fill"></i>
                        </a>
                        <a href="#" class="s-icon">
                        <i class="ri-instagram-fill"></i>
                        </a>
                        <a href="#" class="s-icon">
                        <i class="ri-whatsapp-fill"></i>
                        </a>
                     </div>
                  </div>
               </div>
            </div>
         </div>
         <div class="copyright py-2">
            <div class="container-fluid">
               <p class="mb-0 text-center font-size-14 text-body">STREAMIT - 2021 All Rights Reserved</p>
            </div>
         </div>
      </footer>

Redux/templates/shared/Header.html
{% load static %}
<!-- Header -->
      <header id="main-header">
         <div class="main-header">
            <div class="container-fluid">
               <div class="row">
                  <div class="col-sm-12">
                     <nav class="navbar navbar-expand-lg navbar-light p-0">
                        <a href="#" class="navbar-toggler c-toggler" data-toggle="collapse"
                           data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                           aria-expanded="false" aria-label="Toggle navigation">
                           <div class="navbar-toggler-icon" data-toggle="collapse">
                              <span class="navbar-menu-icon navbar-menu-icon--top"></span>
                              <span class="navbar-menu-icon navbar-menu-icon--middle"></span>
                              <span class="navbar-menu-icon navbar-menu-icon--bottom"></span>
                           </div>
                        </a>
                        <a class="navbar-brand" href="{% url "music:home" %}"> <img class="img-fluid logo" src="{% static 'images/logo.png' %}"
                           alt="streamit" /> </a>
                        <div class="collapse navbar-collapse" id="navbarSupportedContent">
                           <div class="menu-main-menu-container">
                              <ul id="top-menu" class="navbar-nav ml-auto">
                                 <li class="menu-item">
                                    <a href="{% url "music:home" %}">Home</a>
                                 </li>
                                 <li class="menu-item">
                                    <a href="{% url "music:music-list" page=1 %}">All Songs</a>
                                 </li>
                                 <li class="menu-item">
                                    <a href="{% url "music:album-list" page=1 %}">All Albums</a>
                                 </li>
                              </ul>
                           </div>
                        </div>
                        <div class="mobile-more-menu">
                           <a href="javascript:void(0);" class="more-toggle" id="dropdownMenuButton"
                              data-toggle="more-toggle" aria-haspopup="true" aria-expanded="false">
                           <i class="ri-more-line"></i>
                           </a>
                           <div class="more-menu" aria-labelledby="dropdownMenuButton">
                              <div class="navbar-right position-relative">
                                 <ul class="d-flex align-items-center justify-content-end list-inline m-0">
                                    <li>
                                       <a href="#" class="search-toggle">
                                       <i class="ri-search-line"></i>
                                       </a>
                                       <div class="search-box iq-search-bar">
                                          <form action="/search/" class="searchbox">
                                             <div class="form-group position-relative">
                                                <input type="text" name="q" class="text search-input font-size-12"
                                                   placeholder="type here to search...">
                                                <i class="search-link ri-search-line"></i>
                                             </div>
                                          </form>
                                       </div>
                                    </li>
                                    
                                    <li>
                                       <a href="#" class="iq-user-dropdown search-toggle d-flex align-items-center">
                                       <img src="{% static 'images/user/user.jpg' %}" class="img-fluid avatar-40 rounded-circle"
                                          alt="user">
                                       </a>
                                       <div class="iq-sub-dropdown iq-user-dropdown">
                                          <div class="iq-card shadow-none m-0">
                                             <div class="iq-card-body p-0 pl-3 pr-3">
                                                <a href="" class="iq-sub-card setting-dropdown">
                                                   <div class="media align-items-center">
                                                      <div class="right-icon">
                                                         <i class="ri-file-user-line text-primary"></i>
                                                      </div>
                                                      <div class="media-body ml-3">
                                                         <h6 class="mb-0 ">Manage Profile</h6>
                                                      </div>
                                                   </div>
                                                </a>
                                                <a href="" class="iq-sub-card setting-dropdown">
                                                   <div class="media align-items-center">
                                                      <div class="right-icon">
                                                         <i class="ri-settings-4-line text-primary"></i>
                                                      </div>
                                                      <div class="media-body ml-3">
                                                         <h6 class="mb-0 ">Settings</h6>
                                                      </div>
                                                   </div>
                                                </a>
                                                <a href="" class="iq-sub-card setting-dropdown">
                                                   <div class="media align-items-center">
                                                      <div class="right-icon">
                                                         <i class="ri-settings-4-line text-primary"></i>
                                                      </div>
                                                      <div class="media-body ml-3">
                                                         <h6 class="mb-0 ">Pricing Plan</h6>
                                                      </div>
                                                   </div>
                                                </a>
                                                <a href="" class="iq-sub-card setting-dropdown">
                                                   <div class="media align-items-center">
                                                      <div class="right-icon">
                                                         <i class="ri-logout-circle-line text-primary"></i>
                                                      </div>
                                                      <div class="media-body ml-3">
                                                         <h6 class="mb-0">Logout</h6>
                                                      </div>
                                                   </div>
                                                </a>
                                             </div>
                                          </div>
                                       </div>
                                    </li>
                                 </ul>
                              </div>
                           </div>
                        </div>
                        <div class="navbar-right menu-right">
                           <ul class="d-flex align-items-center list-inline m-0">
                              <li class="nav-item nav-icon">
                                 <a href="#" class="search-toggle device-search">
                                 <i class="ri-search-line"></i>
                                 </a>
                                 <div class="search-box iq-search-bar d-search">
                                    <form action="/search/" class="searchbox">
                                       <div class="form-group position-relative">
                                          <input type="text" name="q" class="text search-input font-size-12"
                                             placeholder="type here to search...">
                                          <i class="search-link ri-search-line"></i>
                                       </div>
                                    </form>
                                 </div>
                              </li>
                              <li class="nav-item nav-icon">
                                 <a href="#" class="iq-user-dropdown search-toggle p-0 d-flex align-items-center"
                                    data-toggle="search-toggle">
                                 <img src="{% static 'images/user/user.jpg' %}" class="img-fluid avatar-40 rounded-circle" alt="user">
                                 </a>
                                 <div class="iq-sub-dropdown iq-user-dropdown">
                                    <div class="iq-card shadow-none m-0">
                                       <div class="iq-card-body p-0 pl-3 pr-3">
                                          <a href="" class="iq-sub-card setting-dropdown">
                                             <div class="media align-items-center">
                                                <div class="right-icon">
                                                   <i class="ri-file-user-line text-primary"></i>
                                                </div>
                                                <div class="media-body ml-3">
                                                   <h6 class="mb-0 ">Manage Profile</h6>
                                                </div>
                                             </div>
                                          </a>
                                          <a href="" class="iq-sub-card setting-dropdown">
                                             <div class="media align-items-center">
                                                <div class="right-icon">
                                                   <i class="ri-settings-4-line text-primary"></i>
                                                </div>
                                                <div class="media-body ml-3">
                                                   <h6 class="mb-0 ">Settings</h6>
                                                </div>
                                             </div>
                                          </a>
                                          <a href="" class="iq-sub-card setting-dropdown">
                                             <div class="media align-items-center">
                                                <div class="right-icon">
                                                   <i class="ri-settings-4-line text-primary"></i>
                                                </div>
                                                <div class="media-body ml-3">
                                                   <h6 class="mb-0 ">Pricing Plan</h6>
                                                </div>
                                             </div>
                                          </a>
                                          <a href="" class="iq-sub-card setting-dropdown">
                                             <div class="media align-items-center">
                                                <div class="right-icon">
                                                   <i class="ri-logout-circle-line text-primary"></i>
                                                </div>
                                                <div class="media-body ml-3">
                                                   <h6 class="mb-0 ">Logout</h6>
                                                </div>
                                             </div>
                                          </a>
                                       </div>
                                    </div>
                                 </div>
                              </li>
                           </ul>
                        </div>
                     </nav>
                     <div class="nav-overlay"></div>
                  </div>
               </div>
            </div>
         </div>
      </header>
      <!-- Header End -->

Redux/templates/shared/_Footer_Refrences.html
{% load static %}    
    
    <!-- jQuery, Popper JS -->
      <script src="{% static 'js/jquery-3.4.1.min.js' %}"></script>
      <script src="{% static 'js/popper.min.js' %}"></script>
      <!-- Bootstrap JS -->
      <script src="{% static 'js/bootstrap.min.js' %}"></script>
      <!-- Slick JS -->
      <script src="{% static 'js/slick.min.js' %}"></script>
      <!-- owl carousel Js -->
      <script src="{% static 'js/owl.carousel.min.js' %}"></script>
      <!-- select2 Js -->
      <script src="{% static 'js/select2.min.js' %}"></script>
      <!-- Magnific Popup-->
      <script src="{% static 'js/select2.min.js' %}"></script>
      <!-- Slick Animation-->
      <script src="{% static 'js/slick-animation.min.js' %}"></script>
      <!-- Custom JS-->
      <script src="{% static 'js/custom.js' %}"></script>

Redux/templates/shared/_Header_Refrences.html
{% load static %}      
      
      <!-- Favicon -->
      <link rel="shortcut icon" href="{% static 'images/favicon.ico' %}" />
      <!-- Bootstrap CSS -->
      <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}" />
      <!-- Typography CSS -->
      <link rel="stylesheet" href="{% static 'css/typography.css' %}">
      <!-- Style -->
      <link rel="stylesheet" href="{% static 'css/style.css' %}" />
      <!-- Responsive -->
      <link rel="stylesheet" href="{% static 'css/responsive.css' %}" />

Redux/templates/view_all_album.html
{% extends 'shared/_Main_Layout.html' %}
{% load static %}
{% block content %}
   <!-- MainContent -->
   <div class="main-content">
      <section class="movie-detail container-fluid">
         
      </section>
      <section id="iq-favorites">
         <div class="container-fluid">
            <div class="block-space">
               <div class="row">
                  <div class="col-sm-12 overflow-hidden">
                     <div class="iq-main-header d-flex align-items-center justify-content-between">
                        <h4 class="main-title">All Albums</h4>
                     </div>
                  </div>
               </div>
               <div class="row">
               {% for album in albums %}
                  <div class="col-1-5 col-md-6 col-6 iq-mb-30">
                     <div class="epi-box">
                        <div class="epi-img position-relative">
                           <img src="{{album.img.url}}" class="img-fluid img-zoom" alt="">
                           <div class="episode-play-info">
                              <div class="episode-play">
                                 <a href="{% url "music:album" album.slug %}">
                                    <i class="ri-play-fill"></i>
                                 </a>
                              </div>
                           </div>
                        </div>
                        <div class="epi-desc p-3">
                           <div class="d-flex align-items-center justify-content-between">
                              <span class="text-white">{{album.title|truncatechars:15}}</span>
                           </div>
                           <a href="{% url "music:album" album.slug %}">
                              <h6 class="epi-name text-white mb-0">{{album.desc|truncatechars:15}}
                              </h6>
                           </a>
                        </div>
                     </div>
                  </div>
                {% endfor %}  
               </div>
            </div>
         </div>
      </section>
   </div>   
   <nav class="d-flex justify-content-center" aria-label="Page navigation example">
        <ul class="pagination ">
            {% if albums.has_previous %}
            <li class="page-item"><a class="page-link bg-dark" href="{% url "music:album-list" albums.previous_page_number %}">Previous</a></li>
            {% endif %}
            {% for page in paginator.page_range %}
                <li class="page-item"><a class="page-link bg-dark" href="/{{ page }}">{{ page }}</a></li>
            {% endfor %}
            {% if albums.has_next %}
            <li class="page-item"><a class="page-link bg-dark" href="{% url 'music:album-list' albums.next_page_number %}">Next</a></li>
            {% endif %}
        </ul>
   </nav>
{% endblock %}

Redux/templates/view_all_song.html
{% extends 'shared/_Main_Layout.html' %}
{% load static %}
{% block content %}
   <!-- MainContent -->
   <div class="main-content">
      <section class="movie-detail container-fluid">
         
      </section>
      <section id="iq-favorites">
         <div class="container-fluid">
            <div class="block-space">
               <div class="row">
                  <div class="col-sm-12 overflow-hidden">
                     <div class="iq-main-header d-flex align-items-center justify-content-between">
                        <h4 class="main-title">All Songs</h4>
                     </div>
                  </div>
               </div>
               <div class="row">
               {% for music in musics %}
                  <div class="col-1-5 col-md-6 col-6 iq-mb-30">
                     <div class="epi-box">
                        <div class="epi-img position-relative">
                           <img src="{{music.img.url}}" class="img-fluid img-zoom" alt="">
                           <div class="episode-play-info">
                              <div class="episode-play">
                                 <a href="{% url "music:detail" music.slug %}">
                                    <i class="ri-play-fill"></i>
                                 </a>
                              </div>
                           </div>
                        </div>
                        <div class="epi-desc p-3">
                           <div class="d-flex align-items-center justify-content-between">
                              <span class="text-white">{{music.title|truncatechars:15}}</span>
                           </div>
                           <a href="{% url "music:detail" music.slug %}">
                              <h6 class="epi-name text-white mb-0">{{music.desc|truncatechars:15}}
                              </h6>
                           </a>
                        </div>
                     </div>
                  </div>
                {% endfor %}  
               </div>
            </div>
         </div>
      </section>
   </div>   
   <nav class="d-flex justify-content-center" aria-label="Page navigation example">
        <ul class="pagination ">
            {% if musics.has_previous %}
            <li class="page-item"><a class="page-link bg-dark" href="{% url "music:music-list" musics.previous_page_number %}">Previous</a></li>
            {% endif %}
            {% for page in paginator.page_range %}
                <li class="page-item"><a class="page-link bg-dark" href="/{{ page }}">{{ page }}</a></li>
            {% endfor %}
            {% if musics.has_next %}
            <li class="page-item"><a class="page-link bg-dark" href="{% url 'music:music-list' musics.next_page_number %}">Next</a></li>
            {% endif %}
        </ul>
   </nav>
{% endblock %}